// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq5sVUz_a3Gt8seyM-7m4Em3S5pDCJMaA',
    appId: '1:809588601768:web:bea596f8416962d5b7e39d',
    messagingSenderId: '809588601768',
    projectId: 'cpp-user-side',
    authDomain: 'cpp-user-side.firebaseapp.com',
    storageBucket: 'cpp-user-side.firebasestorage.app',
    measurementId: 'G-SRHBZY5H90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxZnZTxC2tMXjpFE0jttlKqyhtrLp42GI',
    appId: '1:809588601768:android:ab54120faacf1f50b7e39d',
    messagingSenderId: '809588601768',
    projectId: 'cpp-user-side',
    storageBucket: 'cpp-user-side.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY52b36Al5tEW8YUgRaJ74xF9H0DS43MM',
    appId: '1:809588601768:ios:b431cb9fa72f4420b7e39d',
    messagingSenderId: '809588601768',
    projectId: 'cpp-user-side',
    storageBucket: 'cpp-user-side.firebasestorage.app',
    iosBundleId: 'com.example.cpp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY52b36Al5tEW8YUgRaJ74xF9H0DS43MM',
    appId: '1:809588601768:ios:b431cb9fa72f4420b7e39d',
    messagingSenderId: '809588601768',
    projectId: 'cpp-user-side',
    storageBucket: 'cpp-user-side.firebasestorage.app',
    iosBundleId: 'com.example.cpp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq5sVUz_a3Gt8seyM-7m4Em3S5pDCJMaA',
    appId: '1:809588601768:web:7b54c0e677e8853bb7e39d',
    messagingSenderId: '809588601768',
    projectId: 'cpp-user-side',
    authDomain: 'cpp-user-side.firebaseapp.com',
    storageBucket: 'cpp-user-side.firebasestorage.app',
    measurementId: 'G-5JQC8VW5Y5',
  );
}
